### ISSUE TITLE
cannot start v2.1.0

### ISSUE THREAD

**Issue by ralfhauser** [KOST-CECO/KOST-Val#63]
To whom it may concern,

Unfortunately, the validator does not run on my computer.
After double-clicking on the .exe, I quickly see
![image](https://user-images.githubusercontent.com/1681677/145804814-5a660492-b732-4daa-8b3e-5205dfbef045.png)
an then nothing else happens.

When I try to start on the command, line I see

C:\Program Files\Amazon Corretto\jdk11.0.8_10\bin>.\java.exe -jar KOST-Val.jar
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/application/Application
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:59)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 13 more

**Comment by ruedtim** [comment]
has this problem been solved? I am suddenly confronted with the same issue, after months of using the application. It now appears with at least these testet versions: v.2.1.1.0, v.2.1.0.0., v.2.0.5.2.

**Comment by Chlara** [comment]
@ralfhauser 
@ruedtim 
KOST-Val does not run correctly with Amazon Corretto! Amazon Corretto does not support the Webkit from javaFX:  https://github.com/corretto/corretto-8/issues/26 

Can you please try the Beta MSI-Installer. 
[v2.1.1.0 MSI-Installer with Java](https://github.com/KOST-CECO/KOST-Val/releases/tag/v2.1.1.0b)
After that the KOST-Val.exe (GUI) should run again without any Problems and all other Issues from Ralf should be solved.

Claire

**Comment by Chlara** [comment]
KOST-Tools.msi (https://github.com/KOST-CECO/KOST-Val/releases/tag/KOST-Tools_v1.0.3) is used to install KOST-Val together with other archive tools and the appropriate Java.

Accordingly, such errors should be fixed indirectly.
