### ISSUE TITLE
command-line problem with v2.1

### ISSUE THREAD

**Issue by ralfhauser** [KOST-CECO/KOST-Val#64]
java -jar cmd_KOST-Val.jar -sip DOC_t4141.pdf 
KOST-Val
Into the folder specified as logging directory  null/.kost-val_2x/logs cannot been written (possibly missing permissions?). 
An error has occurred. See Console.

**Comment by ralfhauser** [comment]
on debian stable, when I do not only have the jar file, but the entire unzipped folder structure, I get

~/KOST-Val/2.1$ java -jar cmd_KOST-Val.jar --format DOC_t4141.pdfa --de --max
KOST-Val
/home/hauser/KOST-Val/2.1/DOC_t4141.pdfa  
 ! java.lang.UnsatisfiedLinkError: no PdfValidatorAPI in java.library.path: [/usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib] !
 = Invalid
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:61)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.pdftools.pdfvalidator.PdfValidatorAPI
	at ch.kostceco.tools.kostval.controller.Controllervalfile.valFile(Controllervalfile.java:315)
	at ch.kostceco.tools.kostval.KOSTVal.main(KOSTVal.java:251)
	at ch.kostceco.tools.kostval.CmdKOSTVal.main(CmdKOSTVal.java:177)
	... 5 more
~/KOST-Val/2.1$ java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.11+9-post-Debian-1deb10u1, mixed mode, sharing)

**Comment by Chlara** [comment]
KOST-Tools.msi (https://github.com/KOST-CECO/KOST-Val/releases/tag/KOST-Tools_v1.0.3) is used to install KOST-Val together with other archive tools and the appropriate Java.

Accordingly, such errors should be fixed indirectly.
